name: Build and Test on Linux and Mac OS

on: [push]

jobs:
  Linux:

    runs-on: ubuntu-18.04

    steps:
    - name: Install Packages
      run: sudo apt-get install zlib1g-dev make cmake picosat

    - uses: actions/checkout@v1

    - name: mergesat build
      run: make d r p sh lr ld lp lsh

    - name: run CI script
      env:
        RUNOPENWBO: 0
      run: ./tools/ci.sh

  MacOS:

    runs-on: macos-latest

    steps:
    - name: Install Packages
      run: brew install libzip

    - uses: actions/checkout@v1

    - name: mergesat build
      run: make d r sh lr ld lsh
